# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'loginGoogle_aula' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for loginGoogle_aula

	pod 'FirebaseAuth'
	pod 'GoogleSignIn'
	pod 'FacebookCore'
	pod 'FacebookLogin'

end
